"""
Shared pytest fixtures for SightSync backend tests.
Generated by: functional-test-suite agent
Date: 2026-06-05
"""

import datetime
import os

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

# Ensure DATABASE_URL is set before any app import so pydantic-settings doesn't
# fail trying to read a missing .env in CI or a clean checkout.
os.environ.setdefault("DATABASE_URL", "sqlite:///:memory:")
os.environ.setdefault("FRONTEND_URL", "http://localhost:5173")
os.environ.setdefault("CORS_ORIGINS", '["http://localhost:5173","http://localhost:5174","http://127.0.0.1:5173","http://127.0.0.1:5174"]')

from app.database import Base, get_db  # noqa: E402 — must follow env setup
from app.main import app  # noqa: E402


# ---------------------------------------------------------------------------
# Per-test in-memory SQLite engine + session factory
#
# StaticPool forces SQLAlchemy to reuse a single underlying connection for all
# checkouts from the pool.  This is essential for sqlite:///:memory: because
# each *new* connection to that URL starts a completely separate, empty
# database — so without StaticPool, the session that creates the schema and the
# session handed to the TestClient would see different (empty) databases.
# ---------------------------------------------------------------------------

@pytest.fixture()
def db_engine():
    """Fresh in-memory SQLite engine per test — schema is created from scratch."""
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)
    yield engine
    Base.metadata.drop_all(bind=engine)
    engine.dispose()


@pytest.fixture()
def SessionFactory(db_engine):
    """Return a sessionmaker bound to the test engine."""
    return sessionmaker(autocommit=False, autoflush=False, bind=db_engine)


# ---------------------------------------------------------------------------
# Seed helpers
# ---------------------------------------------------------------------------

def _seed_project_and_log(session):
    """Insert a minimal Project and a DailyLog for today.

    Returns (project, daily_log) after flush so IDs are populated.
    """
    from app.models import DailyLog, Project

    project = Project(
        name="Test Project",
        location_city="Tel Aviv",
        latitude=32.0853,
        longitude=34.7818,
    )
    session.add(project)
    session.flush()  # populate project.id

    log = DailyLog(project_id=project.id, date=datetime.date.today())
    session.add(log)
    session.flush()  # populate log.id
    session.commit()
    return project, log


# ---------------------------------------------------------------------------
# TestClient with dependency override
# ---------------------------------------------------------------------------

@pytest.fixture()
def client(SessionFactory):
    """FastAPI TestClient with get_db overridden to use the test session factory."""

    def override_get_db():
        db = SessionFactory()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    with TestClient(app) as c:
        yield c
    app.dependency_overrides.clear()


@pytest.fixture()
def seeded_client(SessionFactory):
    """TestClient with a pre-seeded Project and DailyLog.

    Exposes .project_id and .log_id attributes on the client for convenience.
    Seeds via a dedicated session so the data is committed before the TestClient
    makes requests.
    """
    seed_session = SessionFactory()
    try:
        project, log = _seed_project_and_log(seed_session)
        project_id = project.id
        log_id = log.id
    finally:
        seed_session.close()

    def override_get_db():
        db = SessionFactory()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    with TestClient(app) as c:
        c.project_id = project_id  # type: ignore[attr-defined]
        c.log_id = log_id  # type: ignore[attr-defined]
        yield c
    app.dependency_overrides.clear()
