"""
Shared pytest fixtures for SightSync backend tests.
Generated by: functional-test-suite agent
Date: 2026-06-05
"""

import datetime
import os

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

# Ensure DATABASE_URL is set before any app import so pydantic-settings doesn't
# fail trying to read a missing .env in CI or a clean checkout.
os.environ.setdefault("DATABASE_URL", "sqlite:///:memory:")
os.environ.setdefault("FRONTEND_URL", "http://localhost:5173")
os.environ.setdefault("CORS_ORIGINS", '["http://localhost:5173","http://localhost:5174","http://127.0.0.1:5173","http://127.0.0.1:5174"]')

from app.database import Base, get_db  # noqa: E402 — must follow env setup
from app.main import app  # noqa: E402
from app.models import User, ProjectMember  # noqa: E402
from app.services.auth_service import get_current_user  # noqa: E402


# ---------------------------------------------------------------------------
# Per-test in-memory SQLite engine + session factory
#
# StaticPool forces SQLAlchemy to reuse a single underlying connection for all
# checkouts from the pool.  This is essential for sqlite:///:memory: because
# each *new* connection to that URL starts a completely separate, empty
# database — so without StaticPool, the session that creates the schema and the
# session handed to the TestClient would see different (empty) databases.
# ---------------------------------------------------------------------------

@pytest.fixture()
def db_engine():
    """Fresh in-memory SQLite engine per test — schema is created from scratch."""
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)
    yield engine
    Base.metadata.drop_all(bind=engine)
    engine.dispose()


@pytest.fixture()
def SessionFactory(db_engine):
    """Return a sessionmaker bound to the test engine."""
    return sessionmaker(autocommit=False, autoflush=False, bind=db_engine)


# ---------------------------------------------------------------------------
# Seed helpers
# ---------------------------------------------------------------------------

def _seed_test_user(session, project_id=None):
    user = User(email="test@example.com", name="Test User", password_hash="x")
    session.add(user)
    session.flush()
    if project_id is not None:
        session.add(ProjectMember(user_id=user.id, project_id=project_id, role="owner"))
        session.flush()
    session.commit()
    # Access all attributes while still in session so they're loaded into the instance dict.
    # Then expunge so the object becomes transient and safe to use after session close.
    _ = user.id, user.email, user.name, user.password_hash
    session.expunge(user)
    return user


def _seed_project_and_log(session):
    """Insert a minimal Project and a DailyLog for today.

    Returns (project, daily_log) after flush so IDs are populated.
    """
    from app.models import DailyLog, Project

    project = Project(
        name="Test Project",
        location_city="Tel Aviv",
        latitude=32.0853,
        longitude=34.7818,
    )
    session.add(project)
    session.flush()  # populate project.id

    log = DailyLog(project_id=project.id, date=datetime.date.today())
    session.add(log)
    session.flush()  # populate log.id
    session.commit()
    return project, log


# ---------------------------------------------------------------------------
# TestClient with dependency override
# ---------------------------------------------------------------------------

@pytest.fixture()
def client(SessionFactory):
    """FastAPI TestClient with get_db overridden to use the test session factory."""
    # Seed a test user so auth override has a real User object
    seed_session = SessionFactory()
    try:
        test_user = _seed_test_user(seed_session)
    finally:
        seed_session.close()

    def override_get_db():
        db = SessionFactory()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_current_user] = lambda: test_user
    with TestClient(app) as c:
        yield c
    app.dependency_overrides.clear()


@pytest.fixture()
def seeded_client(SessionFactory):
    """TestClient with a pre-seeded Project and DailyLog.

    Exposes .project_id and .log_id attributes on the client for convenience.
    Seeds via a dedicated session so the data is committed before the TestClient
    makes requests.
    """
    seed_session = SessionFactory()
    try:
        project, log = _seed_project_and_log(seed_session)
        project_id = project.id
        log_id = log.id
        test_user = _seed_test_user(seed_session, project_id=project_id)
    finally:
        seed_session.close()

    def override_get_db():
        db = SessionFactory()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_current_user] = lambda: test_user
    with TestClient(app) as c:
        c.project_id = project_id  # type: ignore[attr-defined]
        c.log_id = log_id  # type: ignore[attr-defined]
        yield c
    app.dependency_overrides.clear()


@pytest.fixture()
def seeded_client_with_tasks(SessionFactory):
    """TestClient with a pre-seeded Project, DailyLog, 3 Tasks, and 2 Dependencies.

    Exposes .project_id, .log_id, .task_ids (list of 3), and .dep_ids (list of 2).
    """
    from app.models import Task, TaskDependency

    seed_session = SessionFactory()
    try:
        project, log = _seed_project_and_log(seed_session)
        project_id = project.id
        log_id = log.id

        today = datetime.date.today()

        task1 = Task(
            project_id=project_id,
            name="Pour Foundation Concrete",
            level_tag="Level 1",
            trade_tag="Concrete",
            start_date=today - datetime.timedelta(days=2),
            duration_days=5,
            end_date=(today - datetime.timedelta(days=2)) + datetime.timedelta(days=5),
            status="in_progress",
            source="manual",
        )
        task2 = Task(
            project_id=project_id,
            name="Install Electrical Conduits",
            level_tag="Level 4",
            trade_tag="Electrical",
            start_date=today,
            duration_days=3,
            end_date=today + datetime.timedelta(days=3),
            status="pending",
            source="manual",
        )
        task3 = Task(
            project_id=project_id,
            name="Plumbing Rough-In",
            level_tag="Level 5",
            trade_tag="Plumbing",
            start_date=today + datetime.timedelta(days=10),
            duration_days=4,
            end_date=today + datetime.timedelta(days=14),
            status="pending",
            source="manual",
        )
        seed_session.add_all([task1, task2, task3])
        seed_session.flush()

        dep1 = TaskDependency(task_id=task2.id, depends_on_task_id=task1.id, lag_days=0)
        dep2 = TaskDependency(task_id=task3.id, depends_on_task_id=task2.id, lag_days=1)
        seed_session.add_all([dep1, dep2])
        seed_session.flush()

        task_ids = [task1.id, task2.id, task3.id]
        dep_ids = [dep1.id, dep2.id]
        seed_session.commit()
        test_user = _seed_test_user(seed_session, project_id=project_id)
    finally:
        seed_session.close()

    def override_get_db():
        db = SessionFactory()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_current_user] = lambda: test_user
    with TestClient(app) as c:
        c.project_id = project_id  # type: ignore[attr-defined]
        c.log_id = log_id  # type: ignore[attr-defined]
        c.task_ids = task_ids  # type: ignore[attr-defined]
        c.dep_ids = dep_ids  # type: ignore[attr-defined]
        yield c
    app.dependency_overrides.clear()
