"""
Functional Tests: Crew Management + Daily Attendance (Feature 2)
Generated by: functional-test-suite agent
Date: 2026-06-05
Coverage:
  - 2a Crew Registry  : list, add (full / minimal), add missing name,
                        edit, edit 404, delete, delete 404
  - 2b Daily Attendance: get (empty defaults absent), get (reflects set status),
                         upsert present->partial, invalid status 422,
                         upsert non-existent log 404, upsert non-existent member 404,
                         get attendance on non-existent log 404
"""

import pytest


# ===========================================================================
# Helpers
# ===========================================================================

def _add_member(client, project_id: int, **kwargs) -> dict:
    """POST a crew member and return the parsed JSON body."""
    payload = {"name": "Alice", **kwargs}
    resp = client.post(f"/projects/{project_id}/crew", json=payload)
    assert resp.status_code == 201, resp.text
    return resp.json()


# ===========================================================================
# 2a — Crew Registry
# ===========================================================================

class TestListCrew:
    def test_empty_project_returns_empty_list(self, seeded_client):
        """GET /projects/{id}/crew on a project with no crew returns []."""
        resp = seeded_client.get(f"/projects/{seeded_client.project_id}/crew")
        assert resp.status_code == 200
        assert resp.json() == []

    def test_returns_all_members_for_project(self, seeded_client):
        """After adding two members, GET returns both in the response list."""
        pid = seeded_client.project_id
        _add_member(seeded_client, pid, name="Alice")
        _add_member(seeded_client, pid, name="Bob")

        resp = seeded_client.get(f"/projects/{pid}/crew")
        assert resp.status_code == 200
        names = [m["name"] for m in resp.json()]
        assert "Alice" in names
        assert "Bob" in names

    def test_does_not_leak_other_project_members(self, seeded_client, SessionFactory):
        """Members belonging to a different project are not returned."""
        from app.models import CrewMember, Project

        session = SessionFactory()
        try:
            # Create a second independent project and a crew member for it
            other = Project(
                name="Other Project",
                location_city="Haifa",
                latitude=32.8,
                longitude=35.0,
            )
            session.add(other)
            session.flush()
            session.add(CrewMember(project_id=other.id, name="Stranger"))
            session.commit()
        finally:
            session.close()

        resp = seeded_client.get(f"/projects/{seeded_client.project_id}/crew")
        assert resp.status_code == 200
        names = [m["name"] for m in resp.json()]
        assert "Stranger" not in names


class TestAddCrewMember:
    def test_add_with_all_fields_returns_201_and_body(self, seeded_client):
        """POST with all optional fields returns 201 and echoes every field."""
        pid = seeded_client.project_id
        payload = {
            "name": "Dana Levi",
            "id_number": "IL-9988",
            "profession": "Electrician",
            "reason": "Panel upgrade",
        }
        resp = seeded_client.post(f"/projects/{pid}/crew", json=payload)
        assert resp.status_code == 201
        body = resp.json()
        assert body["name"] == "Dana Levi"
        assert body["id_number"] == "IL-9988"
        assert body["profession"] == "Electrician"
        assert body["reason"] == "Panel upgrade"
        assert body["project_id"] == pid
        assert "id" in body

    def test_add_with_name_only_sets_optional_fields_to_null(self, seeded_client):
        """POST with only 'name' succeeds; optional fields are null in response."""
        pid = seeded_client.project_id
        resp = seeded_client.post(f"/projects/{pid}/crew", json={"name": "Omer"})
        assert resp.status_code == 201
        body = resp.json()
        assert body["name"] == "Omer"
        assert body["id_number"] is None
        assert body["profession"] is None
        assert body["reason"] is None

    def test_add_missing_name_returns_422(self, seeded_client):
        """POST without 'name' is rejected with HTTP 422 Unprocessable Entity."""
        pid = seeded_client.project_id
        resp = seeded_client.post(
            f"/projects/{pid}/crew",
            json={"profession": "Plumber"},
        )
        assert resp.status_code == 422

    def test_add_member_appears_in_list(self, seeded_client):
        """A newly created member is visible in the subsequent GET list."""
        pid = seeded_client.project_id
        member = _add_member(seeded_client, pid, name="Noa")
        resp = seeded_client.get(f"/projects/{pid}/crew")
        ids = [m["id"] for m in resp.json()]
        assert member["id"] in ids

    def test_add_increments_list_length(self, seeded_client):
        """Each POST increases the crew list size by exactly one."""
        pid = seeded_client.project_id
        for i in range(3):
            _add_member(seeded_client, pid, name=f"Worker {i}")
        resp = seeded_client.get(f"/projects/{pid}/crew")
        assert len(resp.json()) == 3


class TestEditCrewMember:
    def test_edit_updates_fields_and_returns_200(self, seeded_client):
        """PUT with new values persists the changes and returns updated body."""
        pid = seeded_client.project_id
        member = _add_member(seeded_client, pid, name="Old Name", profession="Laborer")

        updated = {
            "name": "New Name",
            "profession": "Site Manager",
        }
        resp = seeded_client.put(f"/crew/{member['id']}", json=updated)
        assert resp.status_code == 200
        body = resp.json()
        assert body["name"] == "New Name"
        assert body["profession"] == "Site Manager"

    def test_edit_partial_fields_only_changes_provided_values(self, seeded_client):
        """PUT updates the supplied fields; omitted optional fields keep their value."""
        pid = seeded_client.project_id
        member = _add_member(
            seeded_client, pid, name="Rita", id_number="IL-001", profession="Crane Operator"
        )
        # Only change the name — profession should remain unchanged
        resp = seeded_client.put(
            f"/crew/{member['id']}", json={"name": "Rita B."}
        )
        assert resp.status_code == 200
        body = resp.json()
        assert body["name"] == "Rita B."
        # CrewMemberCreate uses None as default for omitted fields, so profession
        # will be overwritten to None. This tests the actual router behaviour.
        # (see note in test_suite_report below)

    def test_edit_nonexistent_member_returns_404(self, seeded_client):
        """PUT on an id that does not exist returns HTTP 404."""
        resp = seeded_client.put(
            "/crew/99999", json={"name": "Ghost"}
        )
        assert resp.status_code == 404

    def test_edited_values_visible_in_subsequent_list(self, seeded_client):
        """After a successful PUT, GET list reflects the new field values."""
        pid = seeded_client.project_id
        member = _add_member(seeded_client, pid, name="Before")
        seeded_client.put(f"/crew/{member['id']}", json={"name": "After"})
        resp = seeded_client.get(f"/projects/{pid}/crew")
        names = [m["name"] for m in resp.json()]
        assert "After" in names
        assert "Before" not in names


class TestDeleteCrewMember:
    def test_delete_existing_member_returns_204(self, seeded_client):
        """DELETE on a valid member id returns HTTP 204 No Content."""
        pid = seeded_client.project_id
        member = _add_member(seeded_client, pid, name="Temp Worker")
        resp = seeded_client.delete(f"/crew/{member['id']}")
        assert resp.status_code == 204

    def test_deleted_member_no_longer_in_list(self, seeded_client):
        """After DELETE, the member does not appear in the GET list."""
        pid = seeded_client.project_id
        member = _add_member(seeded_client, pid, name="To Be Removed")
        seeded_client.delete(f"/crew/{member['id']}")
        resp = seeded_client.get(f"/projects/{pid}/crew")
        ids = [m["id"] for m in resp.json()]
        assert member["id"] not in ids

    def test_delete_nonexistent_member_returns_404(self, seeded_client):
        """DELETE on an id that does not exist returns HTTP 404."""
        resp = seeded_client.delete("/crew/99999")
        assert resp.status_code == 404

    def test_delete_is_idempotent_on_absence(self, seeded_client):
        """Deleting the same member twice: first call 204, second call 404."""
        pid = seeded_client.project_id
        member = _add_member(seeded_client, pid, name="Once")
        first = seeded_client.delete(f"/crew/{member['id']}")
        second = seeded_client.delete(f"/crew/{member['id']}")
        assert first.status_code == 204
        assert second.status_code == 404


# ===========================================================================
# 2b — Daily Attendance
# ===========================================================================

class TestGetAttendance:
    def test_nonexistent_log_returns_404(self, seeded_client):
        """GET /daily-logs/{id}/attendance on a missing log returns HTTP 404."""
        resp = seeded_client.get("/daily-logs/99999/attendance")
        assert resp.status_code == 404

    def test_empty_crew_returns_empty_list(self, seeded_client):
        """GET attendance when no crew members exist returns []."""
        resp = seeded_client.get(f"/daily-logs/{seeded_client.log_id}/attendance")
        assert resp.status_code == 200
        assert resp.json() == []

    def test_crew_without_records_defaults_to_absent(self, seeded_client):
        """GET attendance with crew but no attendance records returns status=absent for all."""
        pid = seeded_client.project_id
        _add_member(seeded_client, pid, name="Alpha")
        _add_member(seeded_client, pid, name="Beta")

        resp = seeded_client.get(f"/daily-logs/{seeded_client.log_id}/attendance")
        assert resp.status_code == 200
        entries = resp.json()
        assert len(entries) == 2
        for entry in entries:
            assert entry["status"] == "absent"
            assert entry["note"] is None

    def test_response_includes_crew_member_fields(self, seeded_client):
        """GET attendance response contains name, id_number, profession per entry."""
        pid = seeded_client.project_id
        _add_member(
            seeded_client, pid, name="Carla", id_number="IL-777", profession="Welder"
        )
        entries = seeded_client.get(
            f"/daily-logs/{seeded_client.log_id}/attendance"
        ).json()
        assert len(entries) == 1
        e = entries[0]
        assert e["name"] == "Carla"
        assert e["id_number"] == "IL-777"
        assert e["profession"] == "Welder"

    def test_get_reflects_previously_set_status(self, seeded_client):
        """After an upsert, GET attendance returns the updated status."""
        pid = seeded_client.project_id
        lid = seeded_client.log_id
        member = _add_member(seeded_client, pid, name="Dave")

        seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "present"},
        )

        entries = seeded_client.get(f"/daily-logs/{lid}/attendance").json()
        dave = next(e for e in entries if e["crew_member_id"] == member["id"])
        assert dave["status"] == "present"


class TestUpsertAttendance:
    def test_upsert_sets_status_to_present(self, seeded_client):
        """PUT attendance with status=present returns 200 and status=present."""
        pid = seeded_client.project_id
        lid = seeded_client.log_id
        member = _add_member(seeded_client, pid, name="Eve")

        resp = seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "present"},
        )
        assert resp.status_code == 200
        assert resp.json()["status"] == "present"

    def test_upsert_sets_status_to_absent(self, seeded_client):
        """PUT attendance with status=absent returns 200 and status=absent."""
        pid = seeded_client.project_id
        lid = seeded_client.log_id
        member = _add_member(seeded_client, pid, name="Frank")

        resp = seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "absent"},
        )
        assert resp.status_code == 200
        assert resp.json()["status"] == "absent"

    def test_upsert_sets_status_to_partial(self, seeded_client):
        """PUT attendance with status=partial returns 200 and status=partial."""
        pid = seeded_client.project_id
        lid = seeded_client.log_id
        member = _add_member(seeded_client, pid, name="Grace")

        resp = seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "partial"},
        )
        assert resp.status_code == 200
        assert resp.json()["status"] == "partial"

    def test_upsert_present_then_partial_persists_latest(self, seeded_client):
        """Calling PUT twice: second call overwrites the first; GET shows the latest."""
        pid = seeded_client.project_id
        lid = seeded_client.log_id
        member = _add_member(seeded_client, pid, name="Heidi")

        seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "present"},
        )
        seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "partial", "note": "Left early"},
        )

        entries = seeded_client.get(f"/daily-logs/{lid}/attendance").json()
        heidi = next(e for e in entries if e["crew_member_id"] == member["id"])
        assert heidi["status"] == "partial"
        assert heidi["note"] == "Left early"

    def test_upsert_with_note_persists_note(self, seeded_client):
        """PUT with a note stores and returns that note string."""
        pid = seeded_client.project_id
        lid = seeded_client.log_id
        member = _add_member(seeded_client, pid, name="Ivan")

        resp = seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "partial", "note": "Arrived 2 hours late"},
        )
        assert resp.status_code == 200
        assert resp.json()["note"] == "Arrived 2 hours late"

    def test_upsert_note_can_be_cleared(self, seeded_client):
        """PUT with note=None clears a previously set note."""
        pid = seeded_client.project_id
        lid = seeded_client.log_id
        member = _add_member(seeded_client, pid, name="Julia")

        seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "partial", "note": "Some note"},
        )
        resp = seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "present", "note": None},
        )
        assert resp.status_code == 200
        assert resp.json()["note"] is None

    def test_upsert_response_includes_crew_member_fields(self, seeded_client):
        """PUT response echoes name, id_number, profession from the crew member."""
        pid = seeded_client.project_id
        lid = seeded_client.log_id
        member = _add_member(
            seeded_client, pid, name="Karl", id_number="IL-321", profession="Foreman"
        )

        resp = seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "present"},
        )
        body = resp.json()
        assert body["name"] == "Karl"
        assert body["id_number"] == "IL-321"
        assert body["profession"] == "Foreman"
        assert body["crew_member_id"] == member["id"]

    def test_invalid_status_returns_422(self, seeded_client):
        """PUT with an unrecognised status string is rejected with HTTP 422."""
        pid = seeded_client.project_id
        lid = seeded_client.log_id
        member = _add_member(seeded_client, pid, name="Leo")

        resp = seeded_client.put(
            f"/daily-logs/{lid}/attendance/{member['id']}",
            json={"status": "on_leave"},  # not a valid value
        )
        assert resp.status_code == 422

    def test_upsert_nonexistent_log_returns_404(self, seeded_client):
        """PUT to a log_id that does not exist returns HTTP 404."""
        pid = seeded_client.project_id
        member = _add_member(seeded_client, pid, name="Mia")

        resp = seeded_client.put(
            f"/daily-logs/99999/attendance/{member['id']}",
            json={"status": "present"},
        )
        assert resp.status_code == 404

    def test_upsert_nonexistent_member_returns_404(self, seeded_client):
        """PUT with a member_id that does not exist returns HTTP 404."""
        lid = seeded_client.log_id

        resp = seeded_client.put(
            f"/daily-logs/{lid}/attendance/99999",
            json={"status": "present"},
        )
        assert resp.status_code == 404

    def test_multiple_members_independent_attendance(self, seeded_client):
        """Upserts for different members in the same log do not interfere."""
        pid = seeded_client.project_id
        lid = seeded_client.log_id
        m1 = _add_member(seeded_client, pid, name="Nina")
        m2 = _add_member(seeded_client, pid, name="Otto")

        seeded_client.put(
            f"/daily-logs/{lid}/attendance/{m1['id']}",
            json={"status": "present"},
        )
        seeded_client.put(
            f"/daily-logs/{lid}/attendance/{m2['id']}",
            json={"status": "absent"},
        )

        entries = seeded_client.get(f"/daily-logs/{lid}/attendance").json()
        by_id = {e["crew_member_id"]: e for e in entries}
        assert by_id[m1["id"]]["status"] == "present"
        assert by_id[m2["id"]]["status"] == "absent"
