"""add apartment_tag and room_tag to tasks

Revision ID: 06cc1a127b9c
Revises: 9496245d758b
Create Date: 2026-06-06 11:08:58.629656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06cc1a127b9c'
down_revision: Union[str, None] = '9496245d758b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('apartment_tag', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('room_tag', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'room_tag')
    op.drop_column('tasks', 'apartment_tag')
    # ### end Alembic commands ###
