"""add inventory items and material entry fk

Revision ID: 28cd0db88ab4
Revises: 06cc1a127b9c
Create Date: 2026-06-06 16:20:46.958824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '28cd0db88ab4'
down_revision: Union[str, None] = '06cc1a127b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('min_stock_alert', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('material_entries', sa.Column('inventory_item_id', sa.Integer(), nullable=True))
    # FK is enforced at the ORM level; SQLite does not support ALTER TABLE ADD CONSTRAINT
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_entries', 'inventory_item_id')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
