"""add_photo_upload_sitephoto_tasklogentry_photo_url

Revision ID: 2c68362f4298
Revises: ebbfdb892ef9
Create Date: 2026-06-06 16:52:13.376897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c68362f4298'
down_revision: Union[str, None] = 'ebbfdb892ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task_log_entries', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_log_entries', 'photo_url')
    op.drop_table('site_photos')
    # ### end Alembic commands ###
