"""crew_member_details

Revision ID: 4af695a56d2a
Revises: 883289a5f109
Create Date: 2026-06-05 15:12:00.242100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4af695a56d2a'
down_revision: Union[str, None] = '883289a5f109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_members', sa.Column('id_number', sa.String(length=100), nullable=True))
    op.add_column('crew_members', sa.Column('profession', sa.String(length=200), nullable=True))
    op.add_column('crew_members', sa.Column('reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew_members', 'reason')
    op.drop_column('crew_members', 'profession')
    op.drop_column('crew_members', 'id_number')
    # ### end Alembic commands ###
