"""add_task_models_and_daily_log_submission

Revision ID: 516fb84185f5
Revises: 4af695a56d2a
Create Date: 2026-06-06 01:26:49.437896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '516fb84185f5'
down_revision: Union[str, None] = '4af695a56d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level_tag', sa.String(length=100), nullable=False),
    sa.Column('trade_tag', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_dep')
    )
    op.create_table('task_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('new_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_log_id', 'task_id', name='uq_log_task')
    )
    op.add_column('daily_logs', sa.Column('submitted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('daily_logs', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_logs', 'ai_summary')
    op.drop_column('daily_logs', 'submitted')
    op.drop_table('task_log_entries')
    op.drop_table('task_dependencies')
    op.drop_table('tasks')
    # ### end Alembic commands ###
