"""add_stored_photos_table

Revision ID: cc86040e1fbf
Revises: 2c68362f4298
Create Date: 2026-06-06 18:11:21.741071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc86040e1fbf'
down_revision: Union[str, None] = '2c68362f4298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_photos')
    # ### end Alembic commands ###
