"""add cascade_delay_records

Revision ID: ebbfdb892ef9
Revises: 28cd0db88ab4
Create Date: 2026-06-06 16:39:52.344222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ebbfdb892ef9'
down_revision: Union[str, None] = '28cd0db88ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cascade_delay_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=False),
    sa.Column('triggering_entry_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(length=300), nullable=False),
    sa.Column('old_start_date', sa.Date(), nullable=False),
    sa.Column('new_start_date', sa.Date(), nullable=False),
    sa.Column('days_shifted', sa.Integer(), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggering_entry_id'], ['task_log_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cascade_delay_records')
    # ### end Alembic commands ###
